---
title: "Oct-9"
format: html
---

```{r}
rm(list=ls())
library(tidyverse)
library(here)
```

Exercise 1:
```{r}
tomato <- read.csv(here("data", "tomato_data.csv"))
```

```{r}
tomato[c(3,7,9),]

tomato %>% slice (c(3,7,9)) |> View()
```

```{r}
tomato %>% filter(Treatment == "Fertilizer" & Avg_tomato_weight_g >= 145)
```

Make an output folder
```{r}
dir.create("Outputs")
```

Now save the file
```{r}
write.csv(tomatoes,here("outputs", "tomatoes_fixed.csv"),row.names = FALSE)
# row.names = FALSE prevents R from adding a column of row numbers to the output file
```

```{r}
toms2 <- read.csv(here("Outputs", "tomatoes_fixed.csv"))
```



```{r}
lead <- read.csv(here("data", "NoCoLead.csv")) 
summary(lead)
```

What if we want to know the average number of tests given in the data set
```{r}
lead |> summarise(
  avg_num_tests = mean(num_tests)
) |> View()
```

What is the mean number of tests per year
```{r}
lead_summary <- lead |> 
  group_by(Year) |>
  summarise(
    avg_test_year = mean(num_tests))
```
Whatever you put in your group_by and summarise will become columns


```{r}

```

